language: php
php:
  - 5.3
  - 5.4

notifications:
  email: false
  irc: "irc.freenode.org#fluent-php"

install: travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text
